# Generated by Django 4.0.4 on 2022-05-05 20:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boxes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name_box", models.CharField(max_length=100)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status_box",
                    models.CharField(
                        choices=[("open", "Open"), ("moving", "Moving"), ("close", "Close")],
                        default="open",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ReceiverSender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("box", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.boxes")),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="receiver", to="api.users"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sender", to="api.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("box", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.boxes")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.users")),
            ],
        ),
    ]
